---
.travis.yml:
  rubygems_api_key: "WtAaU2/QJdYpiD9wWGtq9FkkMzJc+8Std+yIQXi8I+uexAVvCXSz2osjdlgzRKW1c09LyEVwR+COxqvOy55sDZUWQq4eynPU3zB+Lcr8xg7VsfdSkjq4oAhXt4FnG65ZvOpOQNpv3sULGhIteAF9Fb4TWKAA8dT5rJfN1PmJ8fw="
